[{:op :const,
  :env {:context :ctx/expr,
        :locals {}},
  :form {:arglists (quote ([x]))},
  :val {:arglists (quote ([x]))},
  :type :map,
  :literal? true,
  :o-tag clojure.lang.PersistentArrayMap,
  :tag clojure.lang.PersistentArrayMap}
 {:children [:meta :expr],
  :meta {:op :const,
         :env {:context :ctx/expr,
               :locals {}},
         :form {:rettag nil},
         :val {:rettag nil},
         :type :map,
         :literal? true,
         :o-tag clojure.lang.PersistentArrayMap,
         :tag clojure.lang.PersistentArrayMap},
  :return-tag java.lang.Number,
  :op :with-meta,
  :env {
        :context :ctx/expr,
        :locals {},
        :ns gen-ast.core},
  :o-tag java.lang.Object,
  :expr {
         :children [:methods],
         :return-tag java.lang.Number,
         :op :fn,
         :env {
               :context :ctx/expr,
               :locals {}},
         :o-tag clojure.lang.AFunction,
         :variadic? false,
         :methods [
                   {:children [:params :body],
                    :loop-id loop_18079,
                    :arglist [x],
                    :params [
                             {:name x__#0,
                              :op :binding,
                              :env {
                                    :context :ctx/expr,
                                    :locals {},
                                    :ns gen-ast.core,
                                    :once false},
                              :o-tag java.lang.Object,
                              :variadic? false,
                              :arg-id 0,
                              :form x,
                              :tag java.lang.Object,
                              :atom #atom[{:tag java.lang.Object} 0x3c7af20c],
                              :local :arg}],
                    :fixed-arity 1,
                    :op :fn-method,
                    :env {
                          :context :ctx/expr,
                          :locals {},
                          :ns gen-ast.core,
                          :once false},
                    :o-tag java.lang.Object,
                    :variadic? false,
                    :form ([x] (+ x 1)),
                    :tag java.lang.Object,
                    :body {:args [
                                  {:children [],
                                   :name x__#0,
                                   :op :local,
                                   :env {
                                         :loop-locals 1,
                                         :locals {x {:form x,
                                                     :name x,
                                                     :variadic? false,
                                                     :op :binding,
                                                     :arg-id 0,
                                                     :local :arg}},
                                         :ns gen-ast.core,
                                         :loop-id loop_18079
                                         :once false,
                                         :context :ctx/expr},
                                   :o-tag java.lang.Object,
                                   :variadic? false,
                                   :arg-id 0,
                                   :form x,
                                   :tag java.lang.Object,
                                   :atom #atom[{:tag java.lang.Object} 0x3c7af20c],
                                   :local :arg,
                                   :assignable? false}
                                  {:op :const,
                                   :env {:loop-locals 1,
                                         :locals {x {:form x,
                                                     :name x,
                                                     :variadic? false,
                                                     :op :binding,
                                                     :arg-id 0,
                                                     :local :arg}},
                                         :ns gen-ast.core,
                                         :loop-id loop_18079,
                                         :once false,
                                         :context :ctx/expr},
                                   :type :number,
                                   :literal? true,
                                   :val 1,
                                   :form 1,
                                   :o-tag long,
                                   :tag long}],
                           :children [:args],
                           :body? true,
                           :method add,
                           :op :static-call,
                           :env {:loop-locals 1,
                                 :locals {x {:form x,
                                             :name x,
                                             :variadic? false,
                                             :op :binding,
                                             :arg-id 0,
                                             :local :arg}},
                                 :ns gen-ast.core,
                                 :loop-id loop_18079,
                                 :once false,
                                 :context :ctx/return},
                           :o-tag java.lang.Number,
                           :class clojure.lang.Numbers,
                           :form (. clojure.lang.Numbers (add x 1)),
                           :tag java.lang.Number,
                           :validated? true,
                           :raw-forms ((do (+ x 1)) (+ x 1))}}],
         :once false,
         :max-fixed-arity 1,
         :form (fn* ([x] (+ x 1))),
         :tag clojure.lang.AFunction,
         :arglists ([x])},
  :form (fn* ([x] (+ x 1))),
  :tag clojure.lang.AFunction,
  :arglists ([x]),
  :raw-forms ((clojure.core/fn ([x] (+ x 1))))}]
